---

- name: task by Vladimir
  user: test
  hosts: ahosts
  gather_facts: false

  tasks:
    - name: creating ./config folder on remote host
      file:
        path:  ./config
        state: directory

    - name: creating ./logs folder on remote host
      file:
        path:  ./logs
        state: directory

    - name: sending text file to remote host
      template:
        src: ./templates/text.txt.j2
        dest: ./config/text.txt        

    - name: sending settings file to remote host
      template:
        src: ./templates/settings.cfg.j2
        dest: ./config/settings.cfg

    - name: sending shell-script file to remote host
      template:
        src: ./templates/script.sh.j2
        dest: ./script.sh
 
    - name: execute shell-script file
      command: sh ./script.sh
      register: scr

    - name: display shell-script file output
      debug:
        var: scr.stdout_lines
